FROM gradle:8.7-jdk17 AS build
WORKDIR /app
COPY --chown=gradle:gradle . .
RUN ./gradlew bootJar --no-daemon -x test

FROM eclipse-temurin:17-jre-alpine
RUN addgroup -S nemogroup && adduser -S nemouser -G nemogroup
WORKDIR /app
COPY --chown=nemouser:nemogroup --from=build /app/build/libs/*-SNAPSHOT.jar app.jar
EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=local
USER nemouser
ENTRYPOINT ["java", "-jar", "app.jar"]
