upstream backend_active {
    server {{ active_backend_container }}:8080;
}

server {
    listen 8080;
    server_name api.stage.rogic.io;

    # Redirect all HTTP requests to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 8443 ssl;
    server_name api.stage.rogic.io;

    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    ssl_certificate /etc/letsencrypt/live/api.stage.rogic.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.stage.rogic.io/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        return 404;
    }

    location /api/ {
        proxy_pass http://backend_active/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_next_upstream error timeout http_502;
    }

    location /actuator/health {
        access_log off;
        proxy_pass http://backend_active/actuator/health;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_next_upstream error timeout http_502;
    }

    location /actuator/prometheus {
        access_log off;
        if ($http_authorization != "Bearer nemologic-metrics-token-2026") {
            return 401;
        }
        proxy_pass http://backend_active/actuator/prometheus;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_next_upstream error timeout http_502;
    }

    location /node-metrics {
        access_log off;
        if ($http_authorization != "Bearer nemologic-metrics-token-2026") {
            return 401;
        }
        proxy_pass http://host.docker.internal:9100/metrics;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
