spring:
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: nemologic

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
