spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nemologic
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: NemologicHikariCP
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
